"""Ideals, and the msolve calls that answer questions about them.

msolve is invoked in Groebner mode only (``-g``), never in solver mode: no
``-P``, no real-root isolation, nothing whose output language has to be guessed
at. Two calls exist here -- ``-g 2`` for a basis and ``-g 1`` for a leading
ideal -- and everything else is derived from those.

Saturation is the one place where the shape of the answer is dictated by that
restriction. ``I : f^oo`` is computed by the Rabinowitsch trick: adjoin a slack
variable ``u`` and the relation ``u*f - 1``. Recovering generators back in the
original ring would need an elimination order, and msolve prints grevlex only,
so :meth:`Ideal.saturate` hands back the ideal *in the extended ring*. That
ideal is not ``I : f^oo`` written in ``R``, but its variety is the graph of
``V(I) \\ V(f)``, isomorphic to it as a scheme -- so emptiness, dimension and
0-dimensional degree all agree, which is everything this library reports.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Iterable, NoReturn, Sequence

from msolveio import RunResult, emit_system, run_groebner
from msolveio.errors import MsolveDied, MsolveOutputError, MsolveTimeout

from .dimdeg import dim_and_degree
from .errors import MsolveInputError, RingMismatch
from .ring import Poly, Ring
from .verdict import Certainty, Kind, Verdict

if TYPE_CHECKING:  # pragma: no cover - import cycle broken at runtime
    from .witness import Witnesses

__all__ = ["Ideal"]


class Ideal:
    """The ideal generated by finitely many polynomials of one :class:`Ring`.

    ``Ideal([R("x*y-1"), R("y^2-x")], ring=R)``. Generators may also be given as
    strings when ``ring`` is supplied. Zero generators are dropped; an ideal
    with no nonzero generators is the zero ideal, and is answered without
    calling msolve at all.
    """

    __slots__ = ("_gens", "_ring")

    def __init__(
        self,
        gens: "Iterable[Poly | str]",
        ring: Ring | None = None,
    ) -> None:
        if isinstance(gens, str):
            raise MsolveInputError(
                "gens must be a sequence of polynomials, not a single string"
            )
        raw_gens = list(gens)
        if ring is None:
            for candidate in raw_gens:
                if isinstance(candidate, Poly):
                    ring = candidate.ring
                    break
            else:
                raise MsolveInputError(
                    "ring= is required when no generator is a Poly"
                )
        if not isinstance(ring, Ring):
            raise RingMismatch(f"ring must be a Ring, got {type(ring).__name__}")
        self._ring = ring
        self._gens = tuple(_coerce(ring, g) for g in raw_gens)

    # -- data ------------------------------------------------------------

    @property
    def gens(self) -> tuple[Poly, ...]:
        """The generators, as given."""
        return self._gens

    @property
    def ring(self) -> Ring:
        """The ring the generators live in."""
        return self._ring

    @property
    def is_zero_ideal(self) -> bool:
        """Whether every generator is zero, so the ideal is ``(0)``."""
        return all(g.is_zero() for g in self._gens)

    def to_msolve(self) -> str:
        """The msolve input file this ideal would be sent as.

        :raises MsolveInputError: if the system is one msolve would mis-parse.
        """
        polys = [g.to_msolve() for g in self._gens if not g.is_zero()] or ["0"]
        return emit_system(
            polys,
            variables=self._ring.names,
            characteristic=self._ring.characteristic,
        )

    # -- Groebner bases --------------------------------------------------

    def groebner(self, timeout: float = 60) -> tuple[Poly, ...]:
        """The reduced grevlex Groebner basis, as polynomials of :attr:`ring`.

        ``(R("1"),)`` for the unit ideal, ``()`` for the zero ideal.

        :param timeout: wall-clock limit for msolve, in seconds.
        :raises MsolveTimeout: if msolve ran out of time.
        :raises MsolveDied: if msolve crashed.
        :raises MsolveOutputError: if msolve's output was not a Groebner basis.
        """
        if self.is_zero_ideal:
            return ()
        result = self._run(gb=2, timeout=timeout)
        self._check_variables(result)
        return tuple(self._ring(entry) for entry in result.output.basis)

    def leading_monomials(self, timeout: float = 60) -> tuple[tuple[int, ...], ...]:
        """Leading monomials of the grevlex Groebner basis, as exponent vectors.

        Over Q this uses ``-g 2`` and takes leading terms of the lifted basis
        (msolve 0.10.1's ``-g 1`` is unlifted). Over a prime field it uses
        ``-g 1``. The unit ideal comes back as the single all-zero vector (the
        constant monomial ``1``); the zero ideal comes back empty.
        """
        if self.is_zero_ideal:
            return ()
        gb = 1 if self._ring.characteristic else 2
        result = self._run(gb=gb, timeout=timeout)
        return self._leading_from(result)

    # -- verdicts --------------------------------------------------------

    def verdict(self, timeout: float = 60) -> Verdict:
        """Emptiness, dimension and 0-dimensional degree in one msolve call.

        Dimension and degree are read combinatorially off the leading
        monomials. Over Q the call is ``-g 2`` so a nonempty result is a
        lifted basis (msolve 0.10.1 skips the lift for ``-g 1``). Over a
        prime field ``-g 1`` is exact. A msolve timeout or crash becomes
        :attr:`Kind.TIMEOUT` or :attr:`Kind.ERROR` rather than an exception;
        bad input still raises.

        Certainty, for msolve 0.10.1: over a prime field, :attr:`
        Certainty.PROVEN` for that field. Over Q, a unit ideal is
        :attr:`Certainty.MODULAR` -- msolve returns after its first modular
        prime and still labels the output characteristic 0 -- while a nonempty
        result is :attr:`Certainty.PROVEN`.
        """
        proven_field = self._ring.characteristic != 0
        if self.is_zero_ideal:
            return Verdict(
                kind=Kind.NONEMPTY,
                dim=self._ring.nvars,
                degree=None,
                certainty=Certainty.PROVEN,
                detail="zero ideal; no msolve call needed",
            )
        try:
            # Over Q, -g 1 is unlifted (first modular prime). Use -g 2 so a
            # nonempty basis is actually over Q; take leading terms in flint.
            result = self._run(gb=2 if not proven_field else 1, timeout=timeout)
        except MsolveTimeout as exc:
            return Verdict(
                kind=Kind.TIMEOUT,
                dim=None,
                degree=None,
                certainty=Certainty.MODULAR,
                detail=str(exc),
            )
        except (MsolveDied, MsolveOutputError) as exc:
            return Verdict(
                kind=Kind.ERROR,
                dim=None,
                degree=None,
                certainty=Certainty.MODULAR,
                detail=str(exc),
            )

        if result.output.unit_ideal:
            return Verdict(
                kind=Kind.EMPTY,
                dim=None,
                degree=None,
                certainty=Certainty.PROVEN if proven_field else Certainty.MODULAR,
                msolve_version=result.msolve_version,
            )

        dim, degree = dim_and_degree(self._leading_from(result), self._ring.nvars)
        return Verdict(
            kind=Kind.NONEMPTY,
            dim=dim,
            degree=degree,
            certainty=Certainty.PROVEN,
            msolve_version=result.msolve_version,
        )

    def contains_one(self, timeout: float = 60) -> Verdict:
        """Is this the unit ideal?

        :returns: the same :class:`Verdict` :meth:`verdict` returns.
            :attr:`Kind.EMPTY` means ``1 in I``: the ideal is the whole ring and
            the system has no solutions. :attr:`Kind.NONEMPTY` means it does
            not.
        """
        return self.verdict(timeout=timeout)

    def radical_member(self, g: "Poly | str", timeout: float = 60) -> Verdict:
        """Is ``g`` in the radical of this ideal?

        Rabinowitsch: ``g in sqrt(I)`` exactly when ``1`` is in
        ``I + (u*g - 1)``. This is an identity over any field, so no assumption
        about algebraic closure is involved.

        :returns: a :class:`Verdict` about ``V(I) \\ V(g)``.
            :attr:`Kind.EMPTY` means yes, ``g`` is in the radical (it vanishes
            on the whole variety). :attr:`Kind.NONEMPTY` means no.
        """
        return self.saturate(g).verdict(timeout=timeout)

    def radical(self) -> NoReturn:
        """Not implemented. Use :meth:`radical_member` instead.

        :raises NotImplementedError: always. Computing a radical needs primary
            decomposition or a 0-dimensional radical algorithm, neither of which
            is in v0.1 and neither of which msolve's Groebner mode provides.
        """
        raise NotImplementedError(
            "qqideal v0.1 does not compute radicals. Radical *membership* is "
            "available as Ideal.radical_member(g), which is a single Groebner "
            "basis computation."
        )

    # -- witness points --------------------------------------------------

    def witness_points(self, timeout: float = 60) -> "Witnesses":
        """Exact witness points of this ideal, when it is zero-dimensional.

        Runs msolve's rational parametrization (``-P``) and factors the
        eliminating polynomial over Q. Each returned point is substituted back
        into every generator with exact arithmetic before it is returned; see
        :mod:`qqideal.witness` for what is proven and what is msolve's claim.

        :param timeout: wall-clock limit for msolve, in seconds.
        :returns: a :class:`~qqideal.Witnesses`; a msolve timeout or crash
            becomes :attr:`~qqideal.WitnessKind.TIMEOUT` or
            :attr:`~qqideal.WitnessKind.ERROR` rather than an exception.
        :raises NotImplementedError: on a prime-field ring; witness extraction
            is a characteristic-0 activity.
        """
        from .witness import extract

        return extract(self, timeout=timeout)

    # -- saturation ------------------------------------------------------

    def saturate(self, f: "Poly | str", timeout: float | None = None) -> "Ideal":
        """``I : f^oo``, as a Rabinowitsch ideal in ``ring[u]``.

        The returned ideal is ``I + (u*f - 1)`` in :attr:`ring` extended by one
        fresh slack variable. Its variety is the graph of ``V(I) \\ V(f)``, so
        emptiness, dimension and 0-dimensional degree match those of
        ``I : f^oo`` in :attr:`ring`. Its *generators* are not the saturated
        ideal written in :attr:`ring`: recovering those needs elimination, and
        msolve's Groebner mode prints grevlex only. v0.1 does not pretend
        otherwise.

        :param f: the polynomial to invert. ``f = 0`` gives the unit ideal,
            which is the right answer: ``D(0)`` is empty.
        :param timeout: accepted for signature stability and unused -- this
            construction is symbolic, and msolve runs only when you ask for a
            basis or a verdict.
        """
        del timeout  # symbolic construction; nothing to time out
        poly = self._coerce(f)
        slack = self._ring.fresh_variable("u")
        extended = self._ring.extend(slack)
        gens = [extended.embed(g) for g in self._gens if not g.is_zero()]
        gens.append(extended.gen(extended.nvars - 1) * extended.embed(poly) - 1)
        return Ideal(gens, ring=extended)

    def colon(self, g: "Poly | str", timeout: float | None = None) -> "Ideal":
        """Alias for :meth:`saturate`: in v0.1 the colon is the saturation.

        ``I : g`` and ``I : g^oo`` differ in general. v0.1 computes only the
        saturation ``I : g^oo``, because that is what the Rabinowitsch trick
        gives without an elimination order, and the two agree on everything this
        library reports about ``V(I) \\ V(g)``. The name is kept so the
        intent reads at the call site; the semantics are :meth:`saturate`'s.
        """
        return self.saturate(g, timeout=timeout)

    # -- internals -------------------------------------------------------

    def _coerce(self, value: "Poly | str") -> Poly:
        return _coerce(self._ring, value)

    def _run(self, *, gb: int, timeout: float) -> RunResult:
        return run_groebner(self.to_msolve(), gb=gb, timeout=timeout)  # type: ignore[arg-type]

    def _check_variables(self, result: RunResult) -> None:
        printed = set(result.output.variables)
        if printed != set(self._ring.names):
            raise MsolveOutputError(
                f"msolve echoed variables {sorted(printed)}, but the ring has "
                f"{sorted(self._ring.names)}"
            )

    def _leading_from(self, result: RunResult) -> tuple[tuple[int, ...], ...]:
        self._check_variables(result)
        return tuple(
            self._ring(entry).leading_monomial() for entry in result.output.basis
        )

    # -- identity --------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Ideal):
            return NotImplemented
        return self._ring == other._ring and self._gens == other._gens

    def __hash__(self) -> int:
        return hash((self._ring, self._gens))

    def __str__(self) -> str:
        inner = ", ".join(str(g) for g in self._gens)
        return f"({inner}) in {self._ring}"

    def __repr__(self) -> str:
        return f"Ideal({[str(g) for g in self._gens]!r}, ring={self._ring!r})"


def _coerce(ring: Ring, value: "Poly | str") -> Poly:
    if isinstance(value, Poly):
        return ring._check(value)
    if isinstance(value, str):
        return ring(value)
    raise MsolveInputError(
        f"expected a Poly or a polynomial string, got {type(value).__name__}"
    )
